# Generated by Django 2.2.6 on 2019-10-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativos_ti',
            name='senha_wifi',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
