# Generated by Django 2.2.6 on 2019-10-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sce', '0003_auto_20191003_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos_ti',
            name='senha_wifi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
