# Generated by Django 2.2.6 on 2019-10-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sce', '0004_auto_20191003_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sce.Ativos_TI'),
        ),
    ]
