# Generated by Django 2.2.6 on 2019-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sce', '0005_auto_20191003_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos_ti',
            name='hd',
            field=models.CharField(blank=True, choices=[('240GB', '240GB'), ('250GB', '250GB'), ('500GB', '500GB'), ('1000GB', '1000GB'), ('2000GB', '2000GB'), ('SSD 240GB', 'SSD 240GB')], default='500GB', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativos_ti',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ativos_ti',
            name='licenca_so',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ativos_ti',
            name='mac',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ativos_ti',
            name='memoria',
            field=models.CharField(blank=True, choices=[('2GB', '2GB'), ('3GB', '3GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB')], default='4GB', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='ativos_ti',
            name='processador',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ativos_ti',
            name='sistema_oper',
            field=models.CharField(blank=True, choices=[('Windows XP Profissional', 'Windows XP Profissional'), ('Windows 7 Home', 'Windows 7 Home'), ('Windows 7 Profissional', 'Windows 7 Profissional'), ('Windows 7 Ultimate', 'Windows 7 Ultimate'), ('Windows 8', 'Windows 8'), ('Windows 10 Profissional', 'Windows 10 Profissional')], default='Windows 10 Profissional', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ativos_ti',
            name='usuario_principal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
